- name: Harden Ubuntu 20.04 Server
  hosts: ubuntu20
  become: yes
  roles:
    - ubuntu2004_cis
  tasks:
    - name: Install fail2ban using apt
      apt: name=fail2ban state=latest update_cache=yes force_apt_get=yes