---
- hosts: docker
  become: yes
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages for Docker
      apt: name={{ docker_required_packages }} state=latest update_cache=yes

    - name: Add Docker GPG key
      apt_key:
        url: "{{ docker_gpg_url }}"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker
      apt: name={{ docker_packges }} state=latest update_cache=yes

    - name: Install Python Docker module
      pip:
        name:
          - docker
          - docker-compose

    - name: Add adminstrator to docker group
      user:
        name: "{{ main_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: u+x,g+x,o+x
